namespace QuanLyMachTu.Controls
{
    partial class TongQuanControl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea1 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.Legend legend1 = new System.Windows.Forms.DataVisualization.Charting.Legend();
            System.Windows.Forms.DataVisualization.Charting.Series series1 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint1 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(100D, 12D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint2 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 30D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint3 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 5D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint4 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 10D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint5 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 50D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint6 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 36D);
            System.Windows.Forms.DataVisualization.Charting.Title title1 = new System.Windows.Forms.DataVisualization.Charting.Title();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea2 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.Legend legend2 = new System.Windows.Forms.DataVisualization.Charting.Legend();
            System.Windows.Forms.DataVisualization.Charting.Series series2 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint7 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(100D, 12D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint8 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 30D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint9 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 5D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint10 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 10D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint11 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 50D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint12 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 36D);
            System.Windows.Forms.DataVisualization.Charting.Title title2 = new System.Windows.Forms.DataVisualization.Charting.Title();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea3 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.Legend legend3 = new System.Windows.Forms.DataVisualization.Charting.Legend();
            System.Windows.Forms.DataVisualization.Charting.Series series3 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint13 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(100D, 12D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint14 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 30D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint15 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 5D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint16 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 10D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint17 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 50D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint18 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 36D);
            System.Windows.Forms.DataVisualization.Charting.Title title3 = new System.Windows.Forms.DataVisualization.Charting.Title();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea4 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.Legend legend4 = new System.Windows.Forms.DataVisualization.Charting.Legend();
            System.Windows.Forms.DataVisualization.Charting.Series series4 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint19 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(100D, 12D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint20 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 30D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint21 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 5D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint22 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 10D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint23 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 50D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint24 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 36D);
            System.Windows.Forms.DataVisualization.Charting.Title title4 = new System.Windows.Forms.DataVisualization.Charting.Title();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea5 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.Legend legend5 = new System.Windows.Forms.DataVisualization.Charting.Legend();
            System.Windows.Forms.DataVisualization.Charting.Series series5 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint25 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(100D, 12D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint26 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 30D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint27 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 5D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint28 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 10D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint29 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 50D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint30 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 36D);
            System.Windows.Forms.DataVisualization.Charting.Title title5 = new System.Windows.Forms.DataVisualization.Charting.Title();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea6 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.Legend legend6 = new System.Windows.Forms.DataVisualization.Charting.Legend();
            System.Windows.Forms.DataVisualization.Charting.Series series6 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint31 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(100D, 12D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint32 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 30D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint33 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 5D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint34 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 10D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint35 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 50D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint36 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 36D);
            System.Windows.Forms.DataVisualization.Charting.Title title6 = new System.Windows.Forms.DataVisualization.Charting.Title();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea7 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.Legend legend7 = new System.Windows.Forms.DataVisualization.Charting.Legend();
            System.Windows.Forms.DataVisualization.Charting.Series series7 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint37 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(1D, 20000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint38 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(2D, 10000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint39 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(3D, 50000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint40 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(4D, 15000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint41 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(5D, 20000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint42 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(6D, 23000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint43 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(7D, 30000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint44 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(8D, 90000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint45 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(10D, 11000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint46 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(11D, 6000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint47 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(12D, 15000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint48 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(9D, 60000000D);
            System.Windows.Forms.DataVisualization.Charting.Series series8 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint49 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(1D, 20000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint50 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(2D, 10000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint51 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(3D, 50000000D);
            System.Windows.Forms.DataVisualization.Charting.Title title7 = new System.Windows.Forms.DataVisualization.Charting.Title();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea8 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.Legend legend8 = new System.Windows.Forms.DataVisualization.Charting.Legend();
            System.Windows.Forms.DataVisualization.Charting.Series series9 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint52 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(1D, 20000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint53 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(2D, 10000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint54 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(3D, 50000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint55 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(4D, 15000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint56 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(5D, 20000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint57 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(6D, 23000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint58 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(7D, 30000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint59 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(8D, 90000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint60 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(10D, 11000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint61 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(11D, 6000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint62 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(12D, 15000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint63 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(9D, 60000000D);
            System.Windows.Forms.DataVisualization.Charting.Series series10 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint64 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(1D, 20000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint65 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(2D, 10000000D);
            System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint66 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(3D, 50000000D);
            System.Windows.Forms.DataVisualization.Charting.Title title8 = new System.Windows.Forms.DataVisualization.Charting.Title();
            panel1 = new Panel();
            tableLayoutPanel5 = new TableLayoutPanel();
            chart_DP_TiTrongTanSuat = new System.Windows.Forms.DataVisualization.Charting.Chart();
            chart_DP_TiTrongDoanhThu = new System.Windows.Forms.DataVisualization.Charting.Chart();
            label4 = new Label();
            tableLayoutPanel4 = new TableLayoutPanel();
            chart_DV_TiTrongTanSuat = new System.Windows.Forms.DataVisualization.Charting.Chart();
            chart_DV_TiTrongDoanhThu = new System.Windows.Forms.DataVisualization.Charting.Chart();
            label3 = new Label();
            tableLayoutPanel1 = new TableLayoutPanel();
            chart_NV_XepHang = new System.Windows.Forms.DataVisualization.Charting.Chart();
            chart_NV_TichCuc = new System.Windows.Forms.DataVisualization.Charting.Chart();
            label2 = new Label();
            tableLayoutPanel2 = new TableLayoutPanel();
            chart_DoanhThu = new System.Windows.Forms.DataVisualization.Charting.Chart();
            label_BenhNhan = new Label();
            tableLayoutPanel3 = new TableLayoutPanel();
            chart_BN_TanSuat = new System.Windows.Forms.DataVisualization.Charting.Chart();
            label1 = new Label();
            panel1.SuspendLayout();
            tableLayoutPanel5.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)chart_DP_TiTrongTanSuat).BeginInit();
            ((System.ComponentModel.ISupportInitialize)chart_DP_TiTrongDoanhThu).BeginInit();
            tableLayoutPanel4.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)chart_DV_TiTrongTanSuat).BeginInit();
            ((System.ComponentModel.ISupportInitialize)chart_DV_TiTrongDoanhThu).BeginInit();
            tableLayoutPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)chart_NV_XepHang).BeginInit();
            ((System.ComponentModel.ISupportInitialize)chart_NV_TichCuc).BeginInit();
            tableLayoutPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)chart_DoanhThu).BeginInit();
            tableLayoutPanel3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)chart_BN_TanSuat).BeginInit();
            SuspendLayout();
            // 
            // panel1
            // 
            panel1.AutoScroll = true;
            panel1.Controls.Add(tableLayoutPanel5);
            panel1.Controls.Add(label4);
            panel1.Controls.Add(tableLayoutPanel4);
            panel1.Controls.Add(label3);
            panel1.Controls.Add(tableLayoutPanel1);
            panel1.Controls.Add(label2);
            panel1.Controls.Add(tableLayoutPanel2);
            panel1.Controls.Add(label_BenhNhan);
            panel1.Controls.Add(tableLayoutPanel3);
            panel1.Controls.Add(label1);
            panel1.Dock = DockStyle.Fill;
            panel1.Location = new Point(0, 0);
            panel1.Margin = new Padding(10);
            panel1.Name = "panel1";
            panel1.Padding = new Padding(10);
            panel1.Size = new Size(1590, 864);
            panel1.TabIndex = 1;
            // 
            // tableLayoutPanel5
            // 
            tableLayoutPanel5.ColumnCount = 2;
            tableLayoutPanel5.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            tableLayoutPanel5.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            tableLayoutPanel5.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 20F));
            tableLayoutPanel5.Controls.Add(chart_DP_TiTrongTanSuat, 1, 0);
            tableLayoutPanel5.Controls.Add(chart_DP_TiTrongDoanhThu, 0, 0);
            tableLayoutPanel5.Dock = DockStyle.Top;
            tableLayoutPanel5.Location = new Point(10, 2170);
            tableLayoutPanel5.Name = "tableLayoutPanel5";
            tableLayoutPanel5.RowCount = 1;
            tableLayoutPanel5.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
            tableLayoutPanel5.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
            tableLayoutPanel5.Size = new Size(1544, 500);
            tableLayoutPanel5.TabIndex = 9;
            // 
            // chart_DP_TiTrongTanSuat
            // 
            chart_DP_TiTrongTanSuat.BackColor = Color.FromArgb(57, 54, 70);
            chart_DP_TiTrongTanSuat.BorderlineColor = Color.Transparent;
            chartArea1.AxisX.IntervalAutoMode = System.Windows.Forms.DataVisualization.Charting.IntervalAutoMode.VariableCount;
            chartArea1.AxisX.IsLabelAutoFit = false;
            chartArea1.AxisX.LabelStyle.Font = new Font("Segoe UI", 10F);
            chartArea1.AxisX.LabelStyle.ForeColor = Color.FromArgb(193, 193, 193);
            chartArea1.AxisX.LineColor = Color.Transparent;
            chartArea1.AxisX.LineWidth = 0;
            chartArea1.AxisX.MajorGrid.Enabled = false;
            chartArea1.AxisX.MajorTickMark.Enabled = false;
            chartArea1.AxisX.Title = "Dịch vụ";
            chartArea1.AxisX.TitleFont = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            chartArea1.AxisX.TitleForeColor = Color.FromArgb(193, 193, 193);
            chartArea1.AxisY.IntervalAutoMode = System.Windows.Forms.DataVisualization.Charting.IntervalAutoMode.VariableCount;
            chartArea1.AxisY.IntervalType = System.Windows.Forms.DataVisualization.Charting.DateTimeIntervalType.Number;
            chartArea1.AxisY.IsLabelAutoFit = false;
            chartArea1.AxisY.LabelStyle.Font = new Font("Segoe UI", 10F);
            chartArea1.AxisY.LabelStyle.ForeColor = Color.FromArgb(193, 193, 193);
            chartArea1.AxisY.LabelStyle.Format = "N0";
            chartArea1.AxisY.LineColor = Color.Transparent;
            chartArea1.AxisY.LineWidth = 0;
            chartArea1.AxisY.MajorGrid.Enabled = false;
            chartArea1.AxisY.MajorTickMark.Enabled = false;
            chartArea1.AxisY.MajorTickMark.LineColor = Color.FromArgb(193, 193, 193);
            chartArea1.AxisY.Title = "Doanh thu (VNĐ)";
            chartArea1.AxisY.TitleFont = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            chartArea1.AxisY.TitleForeColor = Color.FromArgb(193, 193, 193);
            chartArea1.BackColor = Color.FromArgb(57, 54, 70);
            chartArea1.BorderColor = Color.Transparent;
            chartArea1.BorderWidth = 0;
            chartArea1.Name = "ChartArea1";
            chart_DP_TiTrongTanSuat.ChartAreas.Add(chartArea1);
            chart_DP_TiTrongTanSuat.Dock = DockStyle.Fill;
            legend1.BackColor = Color.Transparent;
            legend1.BackSecondaryColor = Color.Transparent;
            legend1.BorderColor = Color.Transparent;
            legend1.Font = new Font("Segoe UI Semibold", 8F, FontStyle.Bold);
            legend1.ForeColor = Color.FromArgb(193, 193, 193);
            legend1.IsTextAutoFit = false;
            legend1.LegendItemOrder = System.Windows.Forms.DataVisualization.Charting.LegendItemOrder.SameAsSeriesOrder;
            legend1.Name = "Legend1";
            legend1.TitleFont = new Font("Segoe UI", 10F);
            chart_DP_TiTrongTanSuat.Legends.Add(legend1);
            chart_DP_TiTrongTanSuat.Location = new Point(777, 5);
            chart_DP_TiTrongTanSuat.Margin = new Padding(5);
            chart_DP_TiTrongTanSuat.Name = "chart_DP_TiTrongTanSuat";
            chart_DP_TiTrongTanSuat.Padding = new Padding(5);
            series1.BackImageTransparentColor = Color.Transparent;
            series1.BackSecondaryColor = Color.Transparent;
            series1.BorderColor = Color.Transparent;
            series1.BorderWidth = 0;
            series1.ChartArea = "ChartArea1";
            series1.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Doughnut;
            series1.Color = Color.FromArgb(128, 128, 255);
            series1.Font = new Font("Segoe UI", 10F);
            series1.IsValueShownAsLabel = true;
            series1.Label = "#PERCENT";
            series1.LabelBackColor = Color.Transparent;
            series1.LabelBorderDashStyle = System.Windows.Forms.DataVisualization.Charting.ChartDashStyle.Dash;
            series1.LabelBorderWidth = 0;
            series1.Legend = "Legend1";
            series1.LegendText = "#VALX";
            series1.Name = "TanSuat";
            series1.Palette = System.Windows.Forms.DataVisualization.Charting.ChartColorPalette.BrightPastel;
            dataPoint1.Color = Color.FromArgb(224, 64, 10);
            dataPoint1.IsValueShownAsLabel = true;
            dataPoint1.Label = "#PERCENT";
            dataPoint1.LabelBackColor = Color.Transparent;
            dataPoint2.Color = Color.FromArgb(26, 59, 105);
            dataPoint2.LabelBackColor = Color.Transparent;
            dataPoint3.Color = Color.FromArgb(5, 100, 146);
            dataPoint3.LabelBackColor = Color.Transparent;
            dataPoint4.Color = Color.FromArgb(65, 140, 240);
            dataPoint4.LabelBackColor = Color.Transparent;
            dataPoint5.Color = Color.FromArgb(222, 158, 27);
            dataPoint5.LabelBackColor = Color.Transparent;
            dataPoint6.Color = Color.FromArgb(71, 181, 34);
            dataPoint6.LabelBackColor = Color.Transparent;
            series1.Points.Add(dataPoint1);
            series1.Points.Add(dataPoint2);
            series1.Points.Add(dataPoint3);
            series1.Points.Add(dataPoint4);
            series1.Points.Add(dataPoint5);
            series1.Points.Add(dataPoint6);
            series1.XValueMember = "TenDP";
            series1.XValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.String;
            series1.YValueMembers = "TanSuat";
            series1.YValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.UInt32;
            chart_DP_TiTrongTanSuat.Series.Add(series1);
            chart_DP_TiTrongTanSuat.Size = new Size(762, 490);
            chart_DP_TiTrongTanSuat.TabIndex = 3;
            chart_DP_TiTrongTanSuat.Text = "chart1";
            title1.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            title1.ForeColor = Color.FromArgb(193, 193, 193);
            title1.Name = "Title1";
            title1.Text = "Biểu đồ tròn tỉ trọng tần suất bán dược phẩm";
            chart_DP_TiTrongTanSuat.Titles.Add(title1);
            // 
            // chart_DP_TiTrongDoanhThu
            // 
            chart_DP_TiTrongDoanhThu.BackColor = Color.FromArgb(57, 54, 70);
            chart_DP_TiTrongDoanhThu.BorderlineColor = Color.Transparent;
            chartArea2.AxisX.IntervalAutoMode = System.Windows.Forms.DataVisualization.Charting.IntervalAutoMode.VariableCount;
            chartArea2.AxisX.IsLabelAutoFit = false;
            chartArea2.AxisX.LabelStyle.Font = new Font("Segoe UI", 10F);
            chartArea2.AxisX.LabelStyle.ForeColor = Color.FromArgb(193, 193, 193);
            chartArea2.AxisX.LineColor = Color.Transparent;
            chartArea2.AxisX.LineWidth = 0;
            chartArea2.AxisX.MajorGrid.Enabled = false;
            chartArea2.AxisX.MajorTickMark.Enabled = false;
            chartArea2.AxisX.Title = "Dịch vụ";
            chartArea2.AxisX.TitleFont = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            chartArea2.AxisX.TitleForeColor = Color.FromArgb(193, 193, 193);
            chartArea2.AxisY.IntervalAutoMode = System.Windows.Forms.DataVisualization.Charting.IntervalAutoMode.VariableCount;
            chartArea2.AxisY.IntervalType = System.Windows.Forms.DataVisualization.Charting.DateTimeIntervalType.Number;
            chartArea2.AxisY.IsLabelAutoFit = false;
            chartArea2.AxisY.LabelStyle.Font = new Font("Segoe UI", 10F);
            chartArea2.AxisY.LabelStyle.ForeColor = Color.FromArgb(193, 193, 193);
            chartArea2.AxisY.LabelStyle.Format = "N0";
            chartArea2.AxisY.LineColor = Color.Transparent;
            chartArea2.AxisY.LineWidth = 0;
            chartArea2.AxisY.MajorGrid.Enabled = false;
            chartArea2.AxisY.MajorTickMark.Enabled = false;
            chartArea2.AxisY.MajorTickMark.LineColor = Color.FromArgb(193, 193, 193);
            chartArea2.AxisY.Title = "Doanh thu (VNĐ)";
            chartArea2.AxisY.TitleFont = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            chartArea2.AxisY.TitleForeColor = Color.FromArgb(193, 193, 193);
            chartArea2.BackColor = Color.FromArgb(57, 54, 70);
            chartArea2.BorderColor = Color.Transparent;
            chartArea2.BorderWidth = 0;
            chartArea2.Name = "ChartArea1";
            chart_DP_TiTrongDoanhThu.ChartAreas.Add(chartArea2);
            chart_DP_TiTrongDoanhThu.Dock = DockStyle.Fill;
            legend2.BackColor = Color.Transparent;
            legend2.BackSecondaryColor = Color.Transparent;
            legend2.BorderColor = Color.Transparent;
            legend2.Font = new Font("Segoe UI Semibold", 8F, FontStyle.Bold);
            legend2.ForeColor = Color.FromArgb(193, 193, 193);
            legend2.IsTextAutoFit = false;
            legend2.LegendItemOrder = System.Windows.Forms.DataVisualization.Charting.LegendItemOrder.SameAsSeriesOrder;
            legend2.Name = "Legend1";
            legend2.TitleFont = new Font("Segoe UI", 10F);
            chart_DP_TiTrongDoanhThu.Legends.Add(legend2);
            chart_DP_TiTrongDoanhThu.Location = new Point(5, 5);
            chart_DP_TiTrongDoanhThu.Margin = new Padding(5);
            chart_DP_TiTrongDoanhThu.Name = "chart_DP_TiTrongDoanhThu";
            chart_DP_TiTrongDoanhThu.Padding = new Padding(5);
            series2.BackImageTransparentColor = Color.Transparent;
            series2.BackSecondaryColor = Color.Transparent;
            series2.BorderColor = Color.Transparent;
            series2.BorderWidth = 0;
            series2.ChartArea = "ChartArea1";
            series2.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Doughnut;
            series2.Color = Color.FromArgb(128, 128, 255);
            series2.Font = new Font("Segoe UI", 10F);
            series2.IsValueShownAsLabel = true;
            series2.Label = "#PERCENT";
            series2.LabelBackColor = Color.Transparent;
            series2.LabelBorderDashStyle = System.Windows.Forms.DataVisualization.Charting.ChartDashStyle.Dash;
            series2.LabelBorderWidth = 0;
            series2.Legend = "Legend1";
            series2.LegendText = "#VALX";
            series2.Name = "DoanhThu";
            series2.Palette = System.Windows.Forms.DataVisualization.Charting.ChartColorPalette.BrightPastel;
            dataPoint7.Color = Color.FromArgb(224, 64, 10);
            dataPoint7.IsValueShownAsLabel = true;
            dataPoint7.Label = "#PERCENT";
            dataPoint7.LabelBackColor = Color.Transparent;
            dataPoint8.Color = Color.FromArgb(26, 59, 105);
            dataPoint8.LabelBackColor = Color.Transparent;
            dataPoint9.Color = Color.FromArgb(5, 100, 146);
            dataPoint9.LabelBackColor = Color.Transparent;
            dataPoint10.Color = Color.FromArgb(65, 140, 240);
            dataPoint10.LabelBackColor = Color.Transparent;
            dataPoint11.Color = Color.FromArgb(222, 158, 27);
            dataPoint11.LabelBackColor = Color.Transparent;
            dataPoint12.Color = Color.FromArgb(71, 181, 34);
            dataPoint12.LabelBackColor = Color.Transparent;
            series2.Points.Add(dataPoint7);
            series2.Points.Add(dataPoint8);
            series2.Points.Add(dataPoint9);
            series2.Points.Add(dataPoint10);
            series2.Points.Add(dataPoint11);
            series2.Points.Add(dataPoint12);
            series2.XValueMember = "TenDP";
            series2.XValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.String;
            series2.YValueMembers = "DoanhThu";
            series2.YValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.UInt32;
            chart_DP_TiTrongDoanhThu.Series.Add(series2);
            chart_DP_TiTrongDoanhThu.Size = new Size(762, 490);
            chart_DP_TiTrongDoanhThu.TabIndex = 2;
            chart_DP_TiTrongDoanhThu.Text = "chart1";
            title2.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            title2.ForeColor = Color.FromArgb(193, 193, 193);
            title2.Name = "Title1";
            title2.Text = "Biểu đồ tỉ trọng doanh thu dược phẩm";
            chart_DP_TiTrongDoanhThu.Titles.Add(title2);
            // 
            // label4
            // 
            label4.BackColor = Color.Transparent;
            label4.Dock = DockStyle.Top;
            label4.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label4.ForeColor = Color.FromArgb(38, 187, 255);
            label4.Location = new Point(10, 2138);
            label4.Name = "label4";
            label4.Size = new Size(1544, 32);
            label4.TabIndex = 8;
            label4.Text = "Dược phẩm";
            label4.TextAlign = ContentAlignment.MiddleCenter;
            label4.Paint += label_Paint;
            // 
            // tableLayoutPanel4
            // 
            tableLayoutPanel4.ColumnCount = 2;
            tableLayoutPanel4.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            tableLayoutPanel4.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            tableLayoutPanel4.Controls.Add(chart_DV_TiTrongTanSuat, 1, 0);
            tableLayoutPanel4.Controls.Add(chart_DV_TiTrongDoanhThu, 0, 0);
            tableLayoutPanel4.Dock = DockStyle.Top;
            tableLayoutPanel4.Location = new Point(10, 1638);
            tableLayoutPanel4.Name = "tableLayoutPanel4";
            tableLayoutPanel4.RowCount = 1;
            tableLayoutPanel4.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
            tableLayoutPanel4.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
            tableLayoutPanel4.Size = new Size(1544, 500);
            tableLayoutPanel4.TabIndex = 7;
            // 
            // chart_DV_TiTrongTanSuat
            // 
            chart_DV_TiTrongTanSuat.BackColor = Color.FromArgb(57, 54, 70);
            chart_DV_TiTrongTanSuat.BorderlineColor = Color.Transparent;
            chartArea3.AxisX.IsLabelAutoFit = false;
            chartArea3.AxisX.LabelStyle.Font = new Font("Segoe UI", 10F);
            chartArea3.AxisX.LabelStyle.ForeColor = Color.FromArgb(193, 193, 193);
            chartArea3.AxisX.LineColor = Color.Transparent;
            chartArea3.AxisX.LineWidth = 0;
            chartArea3.AxisX.MajorGrid.Enabled = false;
            chartArea3.AxisX.MajorTickMark.Enabled = false;
            chartArea3.AxisX.Title = "Dịch vụ";
            chartArea3.AxisX.TitleFont = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            chartArea3.AxisX.TitleForeColor = Color.FromArgb(193, 193, 193);
            chartArea3.AxisY.IntervalType = System.Windows.Forms.DataVisualization.Charting.DateTimeIntervalType.Number;
            chartArea3.AxisY.IsLabelAutoFit = false;
            chartArea3.AxisY.LabelStyle.Font = new Font("Segoe UI", 10F);
            chartArea3.AxisY.LabelStyle.ForeColor = Color.FromArgb(193, 193, 193);
            chartArea3.AxisY.LabelStyle.Format = "N0";
            chartArea3.AxisY.LineColor = Color.Transparent;
            chartArea3.AxisY.LineWidth = 0;
            chartArea3.AxisY.MajorGrid.Enabled = false;
            chartArea3.AxisY.MajorTickMark.Enabled = false;
            chartArea3.AxisY.MajorTickMark.LineColor = Color.FromArgb(193, 193, 193);
            chartArea3.AxisY.Title = "Doanh thu (VNĐ)";
            chartArea3.AxisY.TitleFont = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            chartArea3.AxisY.TitleForeColor = Color.FromArgb(193, 193, 193);
            chartArea3.BackColor = Color.FromArgb(57, 54, 70);
            chartArea3.BorderColor = Color.Transparent;
            chartArea3.BorderWidth = 0;
            chartArea3.Name = "ChartArea1";
            chart_DV_TiTrongTanSuat.ChartAreas.Add(chartArea3);
            chart_DV_TiTrongTanSuat.Dock = DockStyle.Fill;
            legend3.BackColor = Color.Transparent;
            legend3.BackSecondaryColor = Color.Transparent;
            legend3.BorderColor = Color.Transparent;
            legend3.Font = new Font("Segoe UI Semibold", 8F, FontStyle.Bold);
            legend3.ForeColor = Color.FromArgb(193, 193, 193);
            legend3.IsTextAutoFit = false;
            legend3.LegendItemOrder = System.Windows.Forms.DataVisualization.Charting.LegendItemOrder.SameAsSeriesOrder;
            legend3.Name = "Legend1";
            legend3.TitleFont = new Font("Segoe UI", 10F);
            chart_DV_TiTrongTanSuat.Legends.Add(legend3);
            chart_DV_TiTrongTanSuat.Location = new Point(777, 5);
            chart_DV_TiTrongTanSuat.Margin = new Padding(5);
            chart_DV_TiTrongTanSuat.Name = "chart_DV_TiTrongTanSuat";
            chart_DV_TiTrongTanSuat.Padding = new Padding(5);
            series3.BackImageTransparentColor = Color.Transparent;
            series3.BackSecondaryColor = Color.Transparent;
            series3.BorderColor = Color.Transparent;
            series3.BorderWidth = 0;
            series3.ChartArea = "ChartArea1";
            series3.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Doughnut;
            series3.Color = Color.FromArgb(128, 128, 255);
            series3.Font = new Font("Segoe UI", 10F);
            series3.IsValueShownAsLabel = true;
            series3.Label = "#PERCENT";
            series3.LabelBackColor = Color.Transparent;
            series3.LabelBorderDashStyle = System.Windows.Forms.DataVisualization.Charting.ChartDashStyle.Dash;
            series3.LabelBorderWidth = 0;
            series3.Legend = "Legend1";
            series3.LegendText = "#VALX";
            series3.Name = "DoanhThu";
            series3.Palette = System.Windows.Forms.DataVisualization.Charting.ChartColorPalette.BrightPastel;
            dataPoint13.Color = Color.FromArgb(224, 64, 10);
            dataPoint13.IsValueShownAsLabel = true;
            dataPoint13.Label = "#PERCENT";
            dataPoint13.LabelBackColor = Color.Transparent;
            dataPoint14.Color = Color.FromArgb(26, 59, 105);
            dataPoint14.LabelBackColor = Color.Transparent;
            dataPoint15.Color = Color.FromArgb(5, 100, 146);
            dataPoint15.LabelBackColor = Color.Transparent;
            dataPoint16.Color = Color.FromArgb(65, 140, 240);
            dataPoint16.LabelBackColor = Color.Transparent;
            dataPoint17.Color = Color.FromArgb(222, 158, 27);
            dataPoint17.LabelBackColor = Color.Transparent;
            dataPoint18.Color = Color.FromArgb(71, 181, 34);
            dataPoint18.LabelBackColor = Color.Transparent;
            series3.Points.Add(dataPoint13);
            series3.Points.Add(dataPoint14);
            series3.Points.Add(dataPoint15);
            series3.Points.Add(dataPoint16);
            series3.Points.Add(dataPoint17);
            series3.Points.Add(dataPoint18);
            series3.XValueMember = "TenDV";
            series3.XValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.String;
            series3.YValueMembers = "TanSuat";
            series3.YValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.UInt32;
            chart_DV_TiTrongTanSuat.Series.Add(series3);
            chart_DV_TiTrongTanSuat.Size = new Size(762, 490);
            chart_DV_TiTrongTanSuat.TabIndex = 2;
            chart_DV_TiTrongTanSuat.Text = "chart1";
            title3.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            title3.ForeColor = Color.FromArgb(193, 193, 193);
            title3.Name = "Title1";
            title3.Text = "Biểu đồ tròn tỉ trọng tần suất sử dụng dịch vụ";
            chart_DV_TiTrongTanSuat.Titles.Add(title3);
            // 
            // chart_DV_TiTrongDoanhThu
            // 
            chart_DV_TiTrongDoanhThu.BackColor = Color.FromArgb(57, 54, 70);
            chart_DV_TiTrongDoanhThu.BorderlineColor = Color.Transparent;
            chartArea4.AxisX.IntervalAutoMode = System.Windows.Forms.DataVisualization.Charting.IntervalAutoMode.VariableCount;
            chartArea4.AxisX.IsLabelAutoFit = false;
            chartArea4.AxisX.LabelStyle.Font = new Font("Segoe UI", 10F);
            chartArea4.AxisX.LabelStyle.ForeColor = Color.FromArgb(193, 193, 193);
            chartArea4.AxisX.LineColor = Color.Transparent;
            chartArea4.AxisX.LineWidth = 0;
            chartArea4.AxisX.MajorGrid.Enabled = false;
            chartArea4.AxisX.MajorTickMark.Enabled = false;
            chartArea4.AxisX.Title = "Dịch vụ";
            chartArea4.AxisX.TitleFont = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            chartArea4.AxisX.TitleForeColor = Color.FromArgb(193, 193, 193);
            chartArea4.AxisY.IntervalAutoMode = System.Windows.Forms.DataVisualization.Charting.IntervalAutoMode.VariableCount;
            chartArea4.AxisY.IntervalType = System.Windows.Forms.DataVisualization.Charting.DateTimeIntervalType.Number;
            chartArea4.AxisY.IsLabelAutoFit = false;
            chartArea4.AxisY.LabelStyle.Font = new Font("Segoe UI", 10F);
            chartArea4.AxisY.LabelStyle.ForeColor = Color.FromArgb(193, 193, 193);
            chartArea4.AxisY.LabelStyle.Format = "N0";
            chartArea4.AxisY.LineColor = Color.Transparent;
            chartArea4.AxisY.LineWidth = 0;
            chartArea4.AxisY.MajorGrid.Enabled = false;
            chartArea4.AxisY.MajorTickMark.Enabled = false;
            chartArea4.AxisY.MajorTickMark.LineColor = Color.FromArgb(193, 193, 193);
            chartArea4.AxisY.Title = "Doanh thu (VNĐ)";
            chartArea4.AxisY.TitleFont = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            chartArea4.AxisY.TitleForeColor = Color.FromArgb(193, 193, 193);
            chartArea4.BackColor = Color.FromArgb(57, 54, 70);
            chartArea4.BorderColor = Color.Transparent;
            chartArea4.BorderWidth = 0;
            chartArea4.Name = "ChartArea1";
            chart_DV_TiTrongDoanhThu.ChartAreas.Add(chartArea4);
            chart_DV_TiTrongDoanhThu.Dock = DockStyle.Fill;
            legend4.BackColor = Color.Transparent;
            legend4.BackSecondaryColor = Color.Transparent;
            legend4.BorderColor = Color.Transparent;
            legend4.Font = new Font("Segoe UI Semibold", 8F, FontStyle.Bold);
            legend4.ForeColor = Color.FromArgb(193, 193, 193);
            legend4.IsTextAutoFit = false;
            legend4.LegendItemOrder = System.Windows.Forms.DataVisualization.Charting.LegendItemOrder.SameAsSeriesOrder;
            legend4.Name = "Legend1";
            legend4.TitleFont = new Font("Segoe UI", 10F);
            chart_DV_TiTrongDoanhThu.Legends.Add(legend4);
            chart_DV_TiTrongDoanhThu.Location = new Point(5, 5);
            chart_DV_TiTrongDoanhThu.Margin = new Padding(5);
            chart_DV_TiTrongDoanhThu.Name = "chart_DV_TiTrongDoanhThu";
            chart_DV_TiTrongDoanhThu.Padding = new Padding(5);
            series4.BackImageTransparentColor = Color.Transparent;
            series4.BackSecondaryColor = Color.Transparent;
            series4.BorderColor = Color.Transparent;
            series4.BorderWidth = 0;
            series4.ChartArea = "ChartArea1";
            series4.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Doughnut;
            series4.Color = Color.FromArgb(128, 128, 255);
            series4.Font = new Font("Segoe UI", 10F);
            series4.IsValueShownAsLabel = true;
            series4.Label = "#PERCENT";
            series4.LabelBackColor = Color.Transparent;
            series4.LabelBorderDashStyle = System.Windows.Forms.DataVisualization.Charting.ChartDashStyle.Dash;
            series4.LabelBorderWidth = 0;
            series4.Legend = "Legend1";
            series4.LegendText = "#VALX";
            series4.Name = "DoanhThu";
            series4.Palette = System.Windows.Forms.DataVisualization.Charting.ChartColorPalette.BrightPastel;
            dataPoint19.Color = Color.FromArgb(224, 64, 10);
            dataPoint19.IsValueShownAsLabel = true;
            dataPoint19.Label = "#PERCENT";
            dataPoint19.LabelBackColor = Color.Transparent;
            dataPoint20.Color = Color.FromArgb(26, 59, 105);
            dataPoint20.LabelBackColor = Color.Transparent;
            dataPoint21.Color = Color.FromArgb(5, 100, 146);
            dataPoint21.LabelBackColor = Color.Transparent;
            dataPoint22.Color = Color.FromArgb(65, 140, 240);
            dataPoint22.LabelBackColor = Color.Transparent;
            dataPoint23.Color = Color.FromArgb(222, 158, 27);
            dataPoint23.LabelBackColor = Color.Transparent;
            dataPoint24.Color = Color.FromArgb(71, 181, 34);
            dataPoint24.LabelBackColor = Color.Transparent;
            series4.Points.Add(dataPoint19);
            series4.Points.Add(dataPoint20);
            series4.Points.Add(dataPoint21);
            series4.Points.Add(dataPoint22);
            series4.Points.Add(dataPoint23);
            series4.Points.Add(dataPoint24);
            series4.XValueMember = "TenDV";
            series4.XValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.String;
            series4.YValueMembers = "DoanhThu";
            series4.YValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.UInt32;
            chart_DV_TiTrongDoanhThu.Series.Add(series4);
            chart_DV_TiTrongDoanhThu.Size = new Size(762, 490);
            chart_DV_TiTrongDoanhThu.TabIndex = 1;
            chart_DV_TiTrongDoanhThu.Text = "chart1";
            title4.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            title4.ForeColor = Color.FromArgb(193, 193, 193);
            title4.Name = "Title1";
            title4.Text = "Biểu đồ tròn tỉ trọng doanh thu dịch vụ";
            chart_DV_TiTrongDoanhThu.Titles.Add(title4);
            // 
            // label3
            // 
            label3.BackColor = Color.Transparent;
            label3.Dock = DockStyle.Top;
            label3.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label3.ForeColor = Color.FromArgb(38, 187, 255);
            label3.Location = new Point(10, 1606);
            label3.Name = "label3";
            label3.Size = new Size(1544, 32);
            label3.TabIndex = 6;
            label3.Text = "Dịch vụ";
            label3.TextAlign = ContentAlignment.MiddleCenter;
            label3.Paint += label_Paint;
            // 
            // tableLayoutPanel1
            // 
            tableLayoutPanel1.ColumnCount = 2;
            tableLayoutPanel1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            tableLayoutPanel1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            tableLayoutPanel1.Controls.Add(chart_NV_XepHang, 1, 0);
            tableLayoutPanel1.Controls.Add(chart_NV_TichCuc, 0, 0);
            tableLayoutPanel1.Dock = DockStyle.Top;
            tableLayoutPanel1.Location = new Point(10, 1106);
            tableLayoutPanel1.Name = "tableLayoutPanel1";
            tableLayoutPanel1.RowCount = 1;
            tableLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
            tableLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
            tableLayoutPanel1.Size = new Size(1544, 500);
            tableLayoutPanel1.TabIndex = 5;
            // 
            // chart_NV_XepHang
            // 
            chart_NV_XepHang.BackColor = Color.FromArgb(57, 54, 70);
            chart_NV_XepHang.BorderlineColor = Color.Transparent;
            chartArea5.AxisX.IntervalAutoMode = System.Windows.Forms.DataVisualization.Charting.IntervalAutoMode.VariableCount;
            chartArea5.AxisX.IsLabelAutoFit = false;
            chartArea5.AxisX.LabelStyle.Font = new Font("Segoe UI", 10F);
            chartArea5.AxisX.LabelStyle.ForeColor = Color.FromArgb(193, 193, 193);
            chartArea5.AxisX.LineColor = Color.Transparent;
            chartArea5.AxisX.LineWidth = 0;
            chartArea5.AxisX.MajorGrid.Enabled = false;
            chartArea5.AxisX.MajorTickMark.Enabled = false;
            chartArea5.AxisX.Title = "Dịch vụ";
            chartArea5.AxisX.TitleFont = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            chartArea5.AxisX.TitleForeColor = Color.FromArgb(193, 193, 193);
            chartArea5.AxisY.IntervalAutoMode = System.Windows.Forms.DataVisualization.Charting.IntervalAutoMode.VariableCount;
            chartArea5.AxisY.IntervalType = System.Windows.Forms.DataVisualization.Charting.DateTimeIntervalType.Number;
            chartArea5.AxisY.IsLabelAutoFit = false;
            chartArea5.AxisY.LabelStyle.Font = new Font("Segoe UI", 10F);
            chartArea5.AxisY.LabelStyle.ForeColor = Color.FromArgb(193, 193, 193);
            chartArea5.AxisY.LabelStyle.Format = "N0";
            chartArea5.AxisY.LineColor = Color.Transparent;
            chartArea5.AxisY.LineWidth = 0;
            chartArea5.AxisY.MajorGrid.Enabled = false;
            chartArea5.AxisY.MajorTickMark.Enabled = false;
            chartArea5.AxisY.MajorTickMark.LineColor = Color.FromArgb(193, 193, 193);
            chartArea5.AxisY.Title = "Doanh thu (VNĐ)";
            chartArea5.AxisY.TitleFont = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            chartArea5.AxisY.TitleForeColor = Color.FromArgb(193, 193, 193);
            chartArea5.BackColor = Color.FromArgb(57, 54, 70);
            chartArea5.BorderColor = Color.Transparent;
            chartArea5.BorderWidth = 0;
            chartArea5.Name = "ChartArea1";
            chart_NV_XepHang.ChartAreas.Add(chartArea5);
            chart_NV_XepHang.Dock = DockStyle.Fill;
            legend5.BackColor = Color.Transparent;
            legend5.BackSecondaryColor = Color.Transparent;
            legend5.BorderColor = Color.Transparent;
            legend5.Font = new Font("Segoe UI Semibold", 8F, FontStyle.Bold);
            legend5.ForeColor = Color.FromArgb(193, 193, 193);
            legend5.IsTextAutoFit = false;
            legend5.LegendItemOrder = System.Windows.Forms.DataVisualization.Charting.LegendItemOrder.SameAsSeriesOrder;
            legend5.Name = "Legend1";
            legend5.TitleFont = new Font("Segoe UI", 10F);
            chart_NV_XepHang.Legends.Add(legend5);
            chart_NV_XepHang.Location = new Point(777, 5);
            chart_NV_XepHang.Margin = new Padding(5);
            chart_NV_XepHang.Name = "chart_NV_XepHang";
            chart_NV_XepHang.Padding = new Padding(5);
            series5.BackImageTransparentColor = Color.Transparent;
            series5.BackSecondaryColor = Color.Transparent;
            series5.BorderColor = Color.Transparent;
            series5.BorderWidth = 0;
            series5.ChartArea = "ChartArea1";
            series5.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Doughnut;
            series5.Color = Color.FromArgb(128, 128, 255);
            series5.Font = new Font("Segoe UI", 10F);
            series5.IsValueShownAsLabel = true;
            series5.Label = "#PERCENT";
            series5.LabelBackColor = Color.Transparent;
            series5.LabelBorderDashStyle = System.Windows.Forms.DataVisualization.Charting.ChartDashStyle.Dash;
            series5.LabelBorderWidth = 0;
            series5.Legend = "Legend1";
            series5.LegendText = "#VALX: #VAL";
            series5.Name = "DanhGia";
            series5.Palette = System.Windows.Forms.DataVisualization.Charting.ChartColorPalette.Light;
            dataPoint25.Color = Color.FromArgb(224, 64, 10);
            dataPoint25.IsValueShownAsLabel = true;
            dataPoint25.Label = "#PERCENT";
            dataPoint25.LabelBackColor = Color.Transparent;
            dataPoint26.Color = Color.FromArgb(26, 59, 105);
            dataPoint26.LabelBackColor = Color.Transparent;
            dataPoint27.Color = Color.FromArgb(5, 100, 146);
            dataPoint27.LabelBackColor = Color.Transparent;
            dataPoint28.Color = Color.FromArgb(65, 140, 240);
            dataPoint28.LabelBackColor = Color.Transparent;
            dataPoint29.Color = Color.FromArgb(222, 158, 27);
            dataPoint29.LabelBackColor = Color.Transparent;
            dataPoint30.Color = Color.FromArgb(71, 181, 34);
            dataPoint30.LabelBackColor = Color.Transparent;
            series5.Points.Add(dataPoint25);
            series5.Points.Add(dataPoint26);
            series5.Points.Add(dataPoint27);
            series5.Points.Add(dataPoint28);
            series5.Points.Add(dataPoint29);
            series5.Points.Add(dataPoint30);
            series5.XValueMember = "HoTenNV";
            series5.XValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.String;
            series5.YValueMembers = "DanhGia";
            series5.YValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.Single;
            chart_NV_XepHang.Series.Add(series5);
            chart_NV_XepHang.Size = new Size(762, 490);
            chart_NV_XepHang.TabIndex = 3;
            chart_NV_XepHang.Text = "chart1";
            title5.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            title5.ForeColor = Color.FromArgb(193, 193, 193);
            title5.Name = "Title1";
            title5.Text = "Biểu đồ tròn đánh giá nhân viên";
            chart_NV_XepHang.Titles.Add(title5);
            // 
            // chart_NV_TichCuc
            // 
            chart_NV_TichCuc.BackColor = Color.FromArgb(57, 54, 70);
            chart_NV_TichCuc.BorderlineColor = Color.Transparent;
            chartArea6.AxisX.IntervalAutoMode = System.Windows.Forms.DataVisualization.Charting.IntervalAutoMode.VariableCount;
            chartArea6.AxisX.IsLabelAutoFit = false;
            chartArea6.AxisX.LabelStyle.Font = new Font("Segoe UI", 10F);
            chartArea6.AxisX.LabelStyle.ForeColor = Color.FromArgb(193, 193, 193);
            chartArea6.AxisX.LineColor = Color.Transparent;
            chartArea6.AxisX.LineWidth = 0;
            chartArea6.AxisX.MajorGrid.Enabled = false;
            chartArea6.AxisX.MajorTickMark.Enabled = false;
            chartArea6.AxisX.Title = "Dịch vụ";
            chartArea6.AxisX.TitleFont = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            chartArea6.AxisX.TitleForeColor = Color.FromArgb(193, 193, 193);
            chartArea6.AxisY.IntervalAutoMode = System.Windows.Forms.DataVisualization.Charting.IntervalAutoMode.VariableCount;
            chartArea6.AxisY.IntervalType = System.Windows.Forms.DataVisualization.Charting.DateTimeIntervalType.Number;
            chartArea6.AxisY.IsLabelAutoFit = false;
            chartArea6.AxisY.LabelStyle.Font = new Font("Segoe UI", 10F);
            chartArea6.AxisY.LabelStyle.ForeColor = Color.FromArgb(193, 193, 193);
            chartArea6.AxisY.LabelStyle.Format = "N0";
            chartArea6.AxisY.LineColor = Color.Transparent;
            chartArea6.AxisY.LineWidth = 0;
            chartArea6.AxisY.MajorGrid.Enabled = false;
            chartArea6.AxisY.MajorTickMark.Enabled = false;
            chartArea6.AxisY.MajorTickMark.LineColor = Color.FromArgb(193, 193, 193);
            chartArea6.AxisY.Title = "Doanh thu (VNĐ)";
            chartArea6.AxisY.TitleFont = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            chartArea6.AxisY.TitleForeColor = Color.FromArgb(193, 193, 193);
            chartArea6.BackColor = Color.FromArgb(57, 54, 70);
            chartArea6.BorderColor = Color.Transparent;
            chartArea6.BorderWidth = 0;
            chartArea6.Name = "ChartArea1";
            chart_NV_TichCuc.ChartAreas.Add(chartArea6);
            chart_NV_TichCuc.Dock = DockStyle.Fill;
            legend6.BackColor = Color.Transparent;
            legend6.BackSecondaryColor = Color.Transparent;
            legend6.BorderColor = Color.Transparent;
            legend6.Font = new Font("Segoe UI Semibold", 8F, FontStyle.Bold);
            legend6.ForeColor = Color.FromArgb(193, 193, 193);
            legend6.IsTextAutoFit = false;
            legend6.LegendItemOrder = System.Windows.Forms.DataVisualization.Charting.LegendItemOrder.SameAsSeriesOrder;
            legend6.Name = "Legend1";
            legend6.TitleFont = new Font("Segoe UI", 10F);
            chart_NV_TichCuc.Legends.Add(legend6);
            chart_NV_TichCuc.Location = new Point(5, 5);
            chart_NV_TichCuc.Margin = new Padding(5);
            chart_NV_TichCuc.Name = "chart_NV_TichCuc";
            chart_NV_TichCuc.Padding = new Padding(5);
            series6.BackImageTransparentColor = Color.Transparent;
            series6.BackSecondaryColor = Color.Transparent;
            series6.BorderColor = Color.Transparent;
            series6.BorderWidth = 0;
            series6.ChartArea = "ChartArea1";
            series6.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Doughnut;
            series6.Color = Color.FromArgb(128, 128, 255);
            series6.Font = new Font("Segoe UI", 10F);
            series6.IsValueShownAsLabel = true;
            series6.Label = "#PERCENT";
            series6.LabelBackColor = Color.Transparent;
            series6.LabelBorderDashStyle = System.Windows.Forms.DataVisualization.Charting.ChartDashStyle.Dash;
            series6.LabelBorderWidth = 0;
            series6.Legend = "Legend1";
            series6.LegendText = "#VALX: #VAL";
            series6.Name = "TanSuat";
            series6.Palette = System.Windows.Forms.DataVisualization.Charting.ChartColorPalette.BrightPastel;
            dataPoint31.Color = Color.FromArgb(224, 64, 10);
            dataPoint31.IsValueShownAsLabel = true;
            dataPoint31.Label = "#PERCENT";
            dataPoint31.LabelBackColor = Color.Transparent;
            dataPoint32.Color = Color.FromArgb(26, 59, 105);
            dataPoint32.LabelBackColor = Color.Transparent;
            dataPoint33.Color = Color.FromArgb(5, 100, 146);
            dataPoint33.LabelBackColor = Color.Transparent;
            dataPoint34.Color = Color.FromArgb(65, 140, 240);
            dataPoint34.LabelBackColor = Color.Transparent;
            dataPoint35.Color = Color.FromArgb(222, 158, 27);
            dataPoint35.LabelBackColor = Color.Transparent;
            dataPoint36.Color = Color.FromArgb(71, 181, 34);
            dataPoint36.LabelBackColor = Color.Transparent;
            series6.Points.Add(dataPoint31);
            series6.Points.Add(dataPoint32);
            series6.Points.Add(dataPoint33);
            series6.Points.Add(dataPoint34);
            series6.Points.Add(dataPoint35);
            series6.Points.Add(dataPoint36);
            series6.XValueMember = "HoTenNV";
            series6.XValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.String;
            series6.YValueMembers = "TanSuat";
            series6.YValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.UInt32;
            chart_NV_TichCuc.Series.Add(series6);
            chart_NV_TichCuc.Size = new Size(762, 490);
            chart_NV_TichCuc.TabIndex = 2;
            chart_NV_TichCuc.Text = "chart1";
            title6.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            title6.ForeColor = Color.FromArgb(193, 193, 193);
            title6.Name = "Title1";
            title6.Text = "Biểu đồ tròn tần suất làm việc nhân viên";
            chart_NV_TichCuc.Titles.Add(title6);
            // 
            // label2
            // 
            label2.BackColor = Color.Transparent;
            label2.Dock = DockStyle.Top;
            label2.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label2.ForeColor = Color.FromArgb(38, 187, 255);
            label2.Location = new Point(10, 1074);
            label2.Name = "label2";
            label2.Size = new Size(1544, 32);
            label2.TabIndex = 4;
            label2.Text = "Nhân viên";
            label2.TextAlign = ContentAlignment.MiddleCenter;
            label2.Paint += label_Paint;
            // 
            // tableLayoutPanel2
            // 
            tableLayoutPanel2.ColumnCount = 1;
            tableLayoutPanel2.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            tableLayoutPanel2.Controls.Add(chart_DoanhThu, 0, 0);
            tableLayoutPanel2.Dock = DockStyle.Top;
            tableLayoutPanel2.Location = new Point(10, 574);
            tableLayoutPanel2.Name = "tableLayoutPanel2";
            tableLayoutPanel2.Padding = new Padding(5);
            tableLayoutPanel2.RowCount = 1;
            tableLayoutPanel2.RowStyles.Add(new RowStyle());
            tableLayoutPanel2.RowStyles.Add(new RowStyle());
            tableLayoutPanel2.RowStyles.Add(new RowStyle());
            tableLayoutPanel2.Size = new Size(1544, 500);
            tableLayoutPanel2.TabIndex = 1;
            // 
            // chart_DoanhThu
            // 
            chart_DoanhThu.BackColor = Color.FromArgb(57, 54, 70);
            chart_DoanhThu.BorderlineColor = Color.Transparent;
            chartArea7.AxisX.Interval = 1D;
            chartArea7.AxisX.LabelStyle.Font = new Font("Segoe UI", 10F);
            chartArea7.AxisX.LabelStyle.ForeColor = Color.FromArgb(193, 193, 193);
            chartArea7.AxisX.LineColor = Color.Transparent;
            chartArea7.AxisX.LineWidth = 0;
            chartArea7.AxisX.MajorGrid.Enabled = false;
            chartArea7.AxisX.MajorTickMark.Enabled = false;
            chartArea7.AxisX.Maximum = 12D;
            chartArea7.AxisX.Minimum = 1D;
            chartArea7.AxisX.Title = "Tháng";
            chartArea7.AxisX.TitleFont = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            chartArea7.AxisX.TitleForeColor = Color.FromArgb(193, 193, 193);
            chartArea7.AxisY.Interval = 50000000D;
            chartArea7.AxisY.IntervalAutoMode = System.Windows.Forms.DataVisualization.Charting.IntervalAutoMode.VariableCount;
            chartArea7.AxisY.IntervalType = System.Windows.Forms.DataVisualization.Charting.DateTimeIntervalType.Number;
            chartArea7.AxisY.IsLabelAutoFit = false;
            chartArea7.AxisY.LabelStyle.Font = new Font("Segoe UI", 10F);
            chartArea7.AxisY.LabelStyle.ForeColor = Color.FromArgb(193, 193, 193);
            chartArea7.AxisY.LabelStyle.Format = "N0";
            chartArea7.AxisY.LineColor = Color.Transparent;
            chartArea7.AxisY.LineWidth = 0;
            chartArea7.AxisY.MajorGrid.LineColor = Color.FromArgb(125, 125, 125);
            chartArea7.AxisY.MajorGrid.LineWidth = 2;
            chartArea7.AxisY.MajorTickMark.Enabled = false;
            chartArea7.AxisY.MajorTickMark.LineColor = Color.FromArgb(193, 193, 193);
            chartArea7.AxisY.Title = "Doanh thu (VNĐ)";
            chartArea7.AxisY.TitleFont = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            chartArea7.AxisY.TitleForeColor = Color.FromArgb(193, 193, 193);
            chartArea7.BackColor = Color.FromArgb(57, 54, 70);
            chartArea7.BorderColor = Color.Transparent;
            chartArea7.BorderWidth = 0;
            chartArea7.Name = "ChartArea1";
            chart_DoanhThu.ChartAreas.Add(chartArea7);
            chart_DoanhThu.Dock = DockStyle.Fill;
            legend7.BackColor = Color.Transparent;
            legend7.BackSecondaryColor = Color.Transparent;
            legend7.BorderColor = Color.Transparent;
            legend7.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            legend7.ForeColor = Color.FromArgb(193, 193, 193);
            legend7.IsTextAutoFit = false;
            legend7.Name = "Legend1";
            legend7.TitleFont = new Font("Segoe UI", 10F);
            chart_DoanhThu.Legends.Add(legend7);
            chart_DoanhThu.Location = new Point(10, 10);
            chart_DoanhThu.Margin = new Padding(5);
            chart_DoanhThu.Name = "chart_DoanhThu";
            chart_DoanhThu.Padding = new Padding(5);
            series7.BackImageTransparentColor = Color.Transparent;
            series7.BackSecondaryColor = Color.Transparent;
            series7.BorderColor = Color.Transparent;
            series7.BorderWidth = 0;
            series7.ChartArea = "ChartArea1";
            series7.Color = Color.FromArgb(128, 128, 255);
            series7.Font = new Font("Segoe UI", 10F);
            series7.IsValueShownAsLabel = true;
            series7.Label = "#VAL{N0}";
            series7.LabelBackColor = Color.Transparent;
            series7.LabelForeColor = Color.FromArgb(193, 193, 193);
            series7.Legend = "Legend1";
            series7.LegendText = "Doanh thu";
            series7.Name = "DoanhThu";
            dataPoint37.LabelBackColor = Color.Transparent;
            dataPoint38.LabelBackColor = Color.Transparent;
            dataPoint39.LabelBackColor = Color.Transparent;
            dataPoint40.LabelBackColor = Color.Transparent;
            dataPoint41.LabelBackColor = Color.Transparent;
            dataPoint42.LabelBackColor = Color.Transparent;
            dataPoint43.LabelBackColor = Color.Transparent;
            dataPoint44.LabelBackColor = Color.Transparent;
            dataPoint45.LabelBackColor = Color.Transparent;
            dataPoint46.LabelBackColor = Color.Transparent;
            dataPoint47.LabelBackColor = Color.Transparent;
            dataPoint48.LabelBackColor = Color.Transparent;
            series7.Points.Add(dataPoint37);
            series7.Points.Add(dataPoint38);
            series7.Points.Add(dataPoint39);
            series7.Points.Add(dataPoint40);
            series7.Points.Add(dataPoint41);
            series7.Points.Add(dataPoint42);
            series7.Points.Add(dataPoint43);
            series7.Points.Add(dataPoint44);
            series7.Points.Add(dataPoint45);
            series7.Points.Add(dataPoint46);
            series7.Points.Add(dataPoint47);
            series7.Points.Add(dataPoint48);
            series7.XValueMember = "Thang";
            series7.XValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.UInt32;
            series7.YValueMembers = "DoanhThu";
            series7.YValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.UInt64;
            series8.BorderWidth = 4;
            series8.ChartArea = "ChartArea1";
            series8.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Line;
            series8.Color = Color.FromArgb(255, 128, 128);
            series8.Legend = "Legend1";
            series8.LegendText = "Tăng trưởng";
            series8.Name = "TangTruong";
            series8.Points.Add(dataPoint49);
            series8.Points.Add(dataPoint50);
            series8.Points.Add(dataPoint51);
            series8.XValueMember = "Thang";
            series8.XValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.UInt32;
            series8.YValueMembers = "DoanhThu";
            series8.YValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.UInt64;
            chart_DoanhThu.Series.Add(series7);
            chart_DoanhThu.Series.Add(series8);
            chart_DoanhThu.Size = new Size(1524, 480);
            chart_DoanhThu.TabIndex = 0;
            chart_DoanhThu.Text = "chart1";
            title7.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            title7.ForeColor = Color.FromArgb(193, 193, 193);
            title7.Name = "Title1";
            title7.Text = "Biểu đồ cột doanh thu theo tháng";
            chart_DoanhThu.Titles.Add(title7);
            // 
            // label_BenhNhan
            // 
            label_BenhNhan.BackColor = Color.Transparent;
            label_BenhNhan.Dock = DockStyle.Top;
            label_BenhNhan.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label_BenhNhan.ForeColor = Color.FromArgb(38, 187, 255);
            label_BenhNhan.Location = new Point(10, 542);
            label_BenhNhan.Name = "label_BenhNhan";
            label_BenhNhan.Size = new Size(1544, 32);
            label_BenhNhan.TabIndex = 0;
            label_BenhNhan.Text = "Tài chính";
            label_BenhNhan.TextAlign = ContentAlignment.MiddleCenter;
            label_BenhNhan.Paint += label_Paint;
            // 
            // tableLayoutPanel3
            // 
            tableLayoutPanel3.ColumnCount = 1;
            tableLayoutPanel3.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            tableLayoutPanel3.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            tableLayoutPanel3.Controls.Add(chart_BN_TanSuat, 0, 0);
            tableLayoutPanel3.Dock = DockStyle.Top;
            tableLayoutPanel3.Location = new Point(10, 42);
            tableLayoutPanel3.Margin = new Padding(25);
            tableLayoutPanel3.Name = "tableLayoutPanel3";
            tableLayoutPanel3.RowCount = 1;
            tableLayoutPanel3.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
            tableLayoutPanel3.RowStyles.Add(new RowStyle(SizeType.Percent, 50F));
            tableLayoutPanel3.Size = new Size(1544, 500);
            tableLayoutPanel3.TabIndex = 3;
            // 
            // chart_BN_TanSuat
            // 
            chart_BN_TanSuat.BackColor = Color.FromArgb(57, 54, 70);
            chart_BN_TanSuat.BorderlineColor = Color.Transparent;
            chartArea8.AxisX.Interval = 1D;
            chartArea8.AxisX.LabelStyle.Font = new Font("Segoe UI", 10F);
            chartArea8.AxisX.LabelStyle.ForeColor = Color.FromArgb(193, 193, 193);
            chartArea8.AxisX.LineColor = Color.Transparent;
            chartArea8.AxisX.LineWidth = 0;
            chartArea8.AxisX.MajorGrid.Enabled = false;
            chartArea8.AxisX.MajorTickMark.Enabled = false;
            chartArea8.AxisX.Maximum = 12D;
            chartArea8.AxisX.Minimum = 1D;
            chartArea8.AxisX.Title = "Tháng";
            chartArea8.AxisX.TitleFont = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            chartArea8.AxisX.TitleForeColor = Color.FromArgb(193, 193, 193);
            chartArea8.AxisY.Interval = 50D;
            chartArea8.AxisY.IntervalAutoMode = System.Windows.Forms.DataVisualization.Charting.IntervalAutoMode.VariableCount;
            chartArea8.AxisY.IntervalType = System.Windows.Forms.DataVisualization.Charting.DateTimeIntervalType.Number;
            chartArea8.AxisY.IsLabelAutoFit = false;
            chartArea8.AxisY.LabelStyle.Font = new Font("Segoe UI", 10F);
            chartArea8.AxisY.LabelStyle.ForeColor = Color.FromArgb(193, 193, 193);
            chartArea8.AxisY.LabelStyle.Format = "N0";
            chartArea8.AxisY.LineColor = Color.Transparent;
            chartArea8.AxisY.LineWidth = 0;
            chartArea8.AxisY.MajorGrid.LineColor = Color.FromArgb(125, 125, 125);
            chartArea8.AxisY.MajorGrid.LineWidth = 2;
            chartArea8.AxisY.MajorTickMark.Enabled = false;
            chartArea8.AxisY.MajorTickMark.LineColor = Color.FromArgb(193, 193, 193);
            chartArea8.AxisY.Maximum = 100D;
            chartArea8.AxisY.Minimum = 0D;
            chartArea8.AxisY.Title = "Tần suất";
            chartArea8.AxisY.TitleFont = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            chartArea8.AxisY.TitleForeColor = Color.FromArgb(193, 193, 193);
            chartArea8.BackColor = Color.FromArgb(57, 54, 70);
            chartArea8.BorderColor = Color.Transparent;
            chartArea8.BorderWidth = 0;
            chartArea8.Name = "ChartArea1";
            chart_BN_TanSuat.ChartAreas.Add(chartArea8);
            chart_BN_TanSuat.Dock = DockStyle.Fill;
            legend8.BackColor = Color.Transparent;
            legend8.BackSecondaryColor = Color.Transparent;
            legend8.BorderColor = Color.Transparent;
            legend8.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            legend8.ForeColor = Color.FromArgb(193, 193, 193);
            legend8.IsTextAutoFit = false;
            legend8.Name = "Legend1";
            legend8.TitleFont = new Font("Segoe UI", 10F);
            chart_BN_TanSuat.Legends.Add(legend8);
            chart_BN_TanSuat.Location = new Point(5, 5);
            chart_BN_TanSuat.Margin = new Padding(5);
            chart_BN_TanSuat.Name = "chart_BN_TanSuat";
            chart_BN_TanSuat.Padding = new Padding(5);
            series9.BackImageTransparentColor = Color.Transparent;
            series9.BackSecondaryColor = Color.Transparent;
            series9.BorderColor = Color.Transparent;
            series9.BorderWidth = 0;
            series9.ChartArea = "ChartArea1";
            series9.Color = Color.FromArgb(255, 192, 128);
            series9.Font = new Font("Segoe UI", 10F);
            series9.Label = "#VAL";
            series9.LabelBackColor = Color.Transparent;
            series9.LabelForeColor = Color.FromArgb(193, 193, 193);
            series9.Legend = "Legend1";
            series9.LegendText = "Tần suất";
            series9.Name = "TanSuat";
            dataPoint52.LabelBackColor = Color.Transparent;
            dataPoint53.LabelBackColor = Color.Transparent;
            dataPoint54.LabelBackColor = Color.Transparent;
            dataPoint55.LabelBackColor = Color.Transparent;
            dataPoint56.LabelBackColor = Color.Transparent;
            dataPoint57.LabelBackColor = Color.Transparent;
            dataPoint58.LabelBackColor = Color.Transparent;
            dataPoint59.LabelBackColor = Color.Transparent;
            dataPoint60.LabelBackColor = Color.Transparent;
            dataPoint61.LabelBackColor = Color.Transparent;
            dataPoint62.LabelBackColor = Color.Transparent;
            dataPoint63.LabelBackColor = Color.Transparent;
            series9.Points.Add(dataPoint52);
            series9.Points.Add(dataPoint53);
            series9.Points.Add(dataPoint54);
            series9.Points.Add(dataPoint55);
            series9.Points.Add(dataPoint56);
            series9.Points.Add(dataPoint57);
            series9.Points.Add(dataPoint58);
            series9.Points.Add(dataPoint59);
            series9.Points.Add(dataPoint60);
            series9.Points.Add(dataPoint61);
            series9.Points.Add(dataPoint62);
            series9.Points.Add(dataPoint63);
            series9.XValueMember = "Thang";
            series9.XValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.UInt32;
            series9.YValueMembers = "TanSuat";
            series9.YValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.UInt64;
            series10.BorderWidth = 4;
            series10.ChartArea = "ChartArea1";
            series10.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Line;
            series10.Color = Color.FromArgb(255, 128, 128);
            series10.Legend = "Legend1";
            series10.Name = "Tăng trưởng";
            series10.Points.Add(dataPoint64);
            series10.Points.Add(dataPoint65);
            series10.Points.Add(dataPoint66);
            series10.XValueMember = "Thang";
            series10.XValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.UInt32;
            series10.YValueMembers = "TanSuat";
            series10.YValueType = System.Windows.Forms.DataVisualization.Charting.ChartValueType.UInt64;
            chart_BN_TanSuat.Series.Add(series9);
            chart_BN_TanSuat.Series.Add(series10);
            chart_BN_TanSuat.Size = new Size(1534, 490);
            chart_BN_TanSuat.TabIndex = 1;
            chart_BN_TanSuat.Text = "chart_BN_TanSuat";
            title8.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            title8.ForeColor = Color.FromArgb(193, 193, 193);
            title8.Name = "Title1";
            title8.Text = "Biểu đồ cột tần suất bệnh nhân theo tháng";
            chart_BN_TanSuat.Titles.Add(title8);
            // 
            // label1
            // 
            label1.BackColor = Color.Transparent;
            label1.Dock = DockStyle.Top;
            label1.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label1.ForeColor = Color.FromArgb(38, 187, 255);
            label1.Location = new Point(10, 10);
            label1.Name = "label1";
            label1.Size = new Size(1544, 32);
            label1.TabIndex = 2;
            label1.Text = "Bệnh nhân";
            label1.TextAlign = ContentAlignment.MiddleCenter;
            label1.Paint += label_Paint;
            // 
            // TongQuanControl
            // 
            AutoScaleDimensions = new SizeF(10F, 25F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(57, 54, 70);
            Controls.Add(panel1);
            Margin = new Padding(4);
            Name = "TongQuanControl";
            Size = new Size(1590, 864);
            Load += TongQuanControl_Load;
            panel1.ResumeLayout(false);
            tableLayoutPanel5.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)chart_DP_TiTrongTanSuat).EndInit();
            ((System.ComponentModel.ISupportInitialize)chart_DP_TiTrongDoanhThu).EndInit();
            tableLayoutPanel4.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)chart_DV_TiTrongTanSuat).EndInit();
            ((System.ComponentModel.ISupportInitialize)chart_DV_TiTrongDoanhThu).EndInit();
            tableLayoutPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)chart_NV_XepHang).EndInit();
            ((System.ComponentModel.ISupportInitialize)chart_NV_TichCuc).EndInit();
            tableLayoutPanel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)chart_DoanhThu).EndInit();
            tableLayoutPanel3.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)chart_BN_TanSuat).EndInit();
            ResumeLayout(false);
        }

        #endregion
        private Panel panel1;
        private Label label1;
        private TableLayoutPanel tableLayoutPanel2;
        private Label label_BenhNhan;
        private TableLayoutPanel tableLayoutPanel4;
        private Label label3;
        private TableLayoutPanel tableLayoutPanel1;
        private Label label2;
        private TableLayoutPanel tableLayoutPanel5;
        private Label label4;
        private TableLayoutPanel tableLayoutPanel3;
        private System.Windows.Forms.DataVisualization.Charting.Chart chart_DoanhThu;
        private System.Windows.Forms.DataVisualization.Charting.Chart chart_DV_TiTrongDoanhThu;
        private System.Windows.Forms.DataVisualization.Charting.Chart chart_DV_TiTrongTanSuat;
        private System.Windows.Forms.DataVisualization.Charting.Chart chart_DP_TiTrongDoanhThu;
        private System.Windows.Forms.DataVisualization.Charting.Chart chart_DP_TiTrongTanSuat;
        private System.Windows.Forms.DataVisualization.Charting.Chart chart_BN_TanSuat;
        private System.Windows.Forms.DataVisualization.Charting.Chart chart_NV_TichCuc;
        private System.Windows.Forms.DataVisualization.Charting.Chart chart_NV_XepHang;
    }
}
