CREATE DATABASE QUANLYPHONGMACHTU

USE QUANLYPHONGMACHTU

CREATE TABLE BENHNHAN(
	MaBN CHAR(8),
	HoTenBN NVARCHAR(50),
	GioiTinh NVARCHAR(3),
	NgaySinh DATE,
	DoanhSo INT,
	Email VARCHAR(50),
	SDT CHAR(10),
	CONSTRAINT PK_BENHNHAN PRIMARY KEY(MaBN)
)

CREATE TABLE NHANVIEN(
	MaNV CHAR(5),
	HoTenNV NVARCHAR(50),
	GioiTinh NVARCHAR(3),
	NgaySinh DATE,
	Email VARCHAR(50),
	SDT CHAR(10),	
	Luong INT,
	KinhNghiem TINYINT,
	DanhGia DECIMAL(4,2),
	MaKhoa VARCHAR(10),
	CONSTRAINT PK_NHANVIEN PRIMARY KEY(MaNV)
)

CREATE TABLE KHOA(
	MaKhoa VARCHAR(10),
	TenKhoa NVARCHAR(75),
	SoLuong TINYINT,
	MaNV_QuanLy CHAR(5),
	CONSTRAINT PK_KHOA PRIMARY KEY(MaKhoa)
)

CREATE TABLE PHONGKHAM(
	MaPK CHAR(5),
	SoGhe TINYINT,
	TrangThai VARCHAR(5),
	CONSTRAINT PK_PHONGKHAM PRIMARY KEY(MaPK)
)

CREATE TABLE TAIKHOAN(
	MaTK CHAR(10),
	TenTK VARCHAR(30),
	MatKhau VARCHAR(30),
	NgayLap DATE,
	SDT CHAR(10),
	Email VARCHAR(50),
	MaBN CHAR(8),
	CONSTRAINT PK_TAIKHOAN PRIMARY KEY(MaTK)
)

CREATE TABLE LICHKHAM(
	MaLK CHAR(12),
	ThoiDiem DATETIME,
	MaBN CHAR(8),
	MaPK CHAR(5),
	CONSTRAINT PK_LICHKHAM PRIMARY KEY(MaLK)
)

CREATE TABLE DUOCPHAM(
	MaDP CHAR(5),
	TenDP NVARCHAR(50),
	SoLuong SMALLINT,
	MoTa VARCHAR(300),
	GiaNhap INT,
	GiaBan INT,
	XuatXu NVARCHAR(50),	
	DonVi NVARCHAR(10),
	NgayNhap DATE,
	HSD SMALLINT,
	CONSTRAINT PK_DUOCPHAM PRIMARY KEY(MaDP)
)

CREATE TABLE HOSOBENHAN(
	MaHSBA CHAR(8),
	NgayLap DATE,
	KetQuaTongQuat VARCHAR(100),
	MaBN CHAR(8),
	MaNV CHAR(5),
	CONSTRAINT PK_HOSOBENHAN PRIMARY KEY(MaHSBA, NgayLap)
)

CREATE TABLE DICHVU(
	MaDV CHAR(5),
	TenDV NVARCHAR(50),
	ChiPhi INT,
	MoTa VARCHAR(100),
	CONSTRAINT PK_DICHVU PRIMARY KEY(MaDV)
)

CREATE TABLE HOADON(
	MaHD CHAR(10),
	NgayThanhToan DATETIME,
	TongTien INT,
	MaBN CHAR(8),
	MaNV CHAR(5),
	CONSTRAINT PK_HOADON PRIMARY KEY(MaHD)
)

CREATE TABLE CTHD_DichVu(
	MaHD CHAR(10),
	MaDV CHAR(5),
	GiaTien INT,
	CONSTRAINT PK_CTHD_DichVu PRIMARY KEY(MaHD, MaDV)
)

CREATE TABLE CTHD_DuocPham(
	MaHD CHAR(10),
	MaDP CHAR(5),
	SoLuong SMALLINT,
	GiaTien INT,
	DVT NVARCHAR(10),
	CONSTRAINT PK_CTHD_DuocPham PRIMARY KEY(MaHD, MaDP)
)

CREATE TABLE KetQua(
	MaHSBA CHAR(8),
	NgayLap DATE,
	MaDV CHAR(5),
	KetQuaChuanDoan NVARCHAR(50),
	NoiDung NVARCHAR(100),
	CONSTRAINT PK_KetQua PRIMARY KEY(MaHSBA, NgayLap, MaDV)
)

CREATE TABLE BAOCAO(
	MaBaoCao CHAR(6),
	NgayLap DATETIME,
	NoiDung VARCHAR(100),
	MaKhoa VARCHAR(10),
	CONSTRAINT PK_BAOCAO PRIMARY KEY(MaBaoCao)
)

CREATE TABLE LamViec(
	MaNV CHAR(5),
	MaPK CHAR(5),
	ThoiGianBD TIME,
	ThoiGianKT TIME,
	CONSTRAINT PK_LamViec PRIMARY KEY(MaNV, MaPK)
)

CREATE TABLE PhongKham_DichVu(
	MaDV CHAR(5),
	MaPK CHAR(5),
	TinhTrang VARCHAR(5),
	CONSTRAINT PK_PhongKham_DichVu PRIMARY KEY(MaDV, MaPK)
)

ALTER TABLE TAIKHOAN
ADD CONSTRAINT FK_TAIKHOAN_MaBN FOREIGN KEY(MaBN) REFERENCES BENHNHAN(MaBN)

ALTER TABLE LICHKHAM
ADD CONSTRAINT FK_LICHKHAM_MaBN FOREIGN KEY(MaBN) REFERENCES BENHNHAN(MaBN)
ALTER TABLE LICHKHAM
ADD CONSTRAINT FK_LICHKHAM_MaPK FOREIGN KEY(MaPK) REFERENCES PHONGKHAM(MaPK)

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_MaKhoa FOREIGN KEY(MaKhoa) REFERENCES KHOA(MaKhoa)

ALTER TABLE KHOA
ADD CONSTRAINT FK_KHOA_MaNV_QuanLy FOREIGN KEY(MaNV_QuanLy) REFERENCES NHANVIEN(MaNV)

ALTER TABLE BAOCAO
ADD CONSTRAINT FK_BAOCAO_MaKhoa FOREIGN KEY(MaKhoa) REFERENCES KHOA(MaKhoa)

ALTER TABLE HOSOBENHAN
ADD CONSTRAINT FK_HOSOBENHAN_MaBN FOREIGN KEY(MaBN) REFERENCES BENHNHAN(MaBN)
ALTER TABLE HOSOBENHAN
ADD CONSTRAINT FK_HOSOBENHAN_MaNV FOREIGN KEY(MaNV) REFERENCES NHANVIEN(MaNV)

ALTER TABLE CTHD_DuocPham
ADD CONSTRAINT FK_CTHD_DuocPham_MaHD FOREIGN KEY(MaHD) REFERENCES HOADON(MaHD)
ALTER TABLE CTHD_DuocPham
ADD CONSTRAINT FK_CTHD_DuocPham_MaDP FOREIGN KEY(MaDP) REFERENCES DUOCPHAM(MaDP)

ALTER TABLE CTHD_DichVu
ADD CONSTRAINT FK_CTHD_DichVu_MaHD FOREIGN KEY(MaHD) REFERENCES HOADON(MaHD)
ALTER TABLE CTHD_DichVu
ADD CONSTRAINT FK_CTHD_DichVu_MaDV FOREIGN KEY(MaDV) REFERENCES DICHVU(MaDV)

ALTER TABLE KetQua
ADD CONSTRAINT FK_KetQua_MaHSBA FOREIGN KEY(MaHSBA, NgayLap) REFERENCES HOSOBENHAN(MaHSBA, NgayLap)
ALTER TABLE KetQua
ADD CONSTRAINT FK_KetQua_MaDV FOREIGN KEY(MaDV) REFERENCES DICHVU(MaDV)

ALTER TABLE LamViec
ADD CONSTRAINT FK_LamViec_MaNV FOREIGN KEY(MaNV) REFERENCES NHANVIEN(MaNV)
ALTER TABLE LamViec
ADD CONSTRAINT FK_LamViec_MaPK FOREIGN KEY(MaPK) REFERENCES PHONGKHAM(MaPK)

ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_MaBN FOREIGN KEY(MaBN) REFERENCES BENHNHAN(MaBN)
ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_MaNV FOREIGN KEY(MaNV) REFERENCES NHANVIEN(MaNV)

ALTER TABLE PhongKham_DichVu
ADD CONSTRAINT FK_PhongKham_DichVu_MaDV FOREIGN KEY(MaDV) REFERENCES DICHVU(MaDV)
ALTER TABLE PhongKham_DichVu
ADD CONSTRAINT FK_PhongKham_DichVu_MaPK FOREIGN KEY(MaPK) REFERENCES PHONGKHAM(MaPK)

EXEC sp_configure 'show advanced options', 1;
RECONFIGURE;
EXEC sp_configure 'Ad Hoc Distributed Queries', 1;
RECONFIGURE;

SELECT * FROM CTHD_DuocPham  

INSERT INTO CTHD_DuocPham 
SELECT TOP 7 MaHD, MaDP, SoLuong, GiaTien, DVT
FROM OPENROWSET('Microsoft.ACE.OLEDB.12.0',
				'Excel 12.0;Database=C:\Users\pc\Desktop\sample_data.xlsx;HDR=YES',
				'SELECT * FROM [Sheet1$]')

UPDATE DUOCPHAM
SET XuatXu = (SELECT XuatXu
			  FROM OPENROWSET('Microsoft.ACE.OLEDB.12.0',
				'Excel 12.0;Database=C:\Users\pc\Desktop\sample_data.xlsx;HDR=YES',
				'SELECT * FROM [Sheet1$]') A
			  WHERE A.MaDP = DUOCPHAM.MaDP)

UPDATE HOADON
SET TongTien = COALESCE((SELECT SUM(GiaTien)
						 FROM CTHD_DichVu
						 WHERE CTHD_DichVu.MaHD = HOADON.MaHD), 0)
				+
				COALESCE((SELECT SUM(GiaTien)
						  FROM CTHD_DuocPham
						  WHERE CTHD_DuocPham.MaHD = HOADON.MaHD), 0)

SELECT * FROM DUOCPHAM

SELECT * FROM NHANVIEN NV
INNER JOIN HOADON HD ON HD.MaNV = NV.MaNV
INNER JOIN HOSOBENHAN HS ON HS.MaNV = NV.MaNV

SELECT BN.MaBN, HoTenBN, GioiTinh, NgaySinh, DoanhSo, Email, SDT, MaHSBA, MaHD
FROM BENHNHAN BN
LEFT JOIN HOSOBENHAN HS ON HS.MaBN = BN.MaBN
LEFT JOIN HOADON HD ON HD.MaBN= BN.MaBN
WHERE 1 = 1
